package webshare

import (
	"context"
	"net/http"
	"strconv"
	"time"
)

// TwoFactorAuthService exposes the two-factor authentication operations.
// Two-factor authentication only applies to login tokens; API keys are never
// challenged. When 2FA is required, any API call returns 403 with code
// "2fa_needed"; submit a code with SubmitCode and replay the request.
//
// The method management endpoints (at least GetMethod) are
// session-token-only: calling them with an API key returns a 403 with code
// "api_key_not_allowed" ("Cannot query this API endpoint with an API key.").
type TwoFactorAuthService struct {
	client *Client
}

// TwoFactorMethodType is the kind of 2FA method.
type TwoFactorMethodType string

// Two-factor method types.
const (
	// MethodEmailCode delivers codes via email. Enabled by default and
	// activates instantly.
	MethodEmailCode TwoFactorMethodType = "email_code"
	// MethodDeviceTOTP uses a TOTP device; it requires activation with two
	// consecutive codes.
	MethodDeviceTOTP TwoFactorMethodType = "device_totp"
)

// TwoFactorMethod is a 2FA method of the account. Each account has exactly
// one active method.
type TwoFactorMethod struct {
	// ID is the unique identifier of the 2FA method instance.
	ID int `json:"id"`
	// Type is the method type.
	Type TwoFactorMethodType `json:"type"`
	// Active reports whether this is the active 2FA method for the account.
	Active bool `json:"active"`
	// SecretKey is the hex-formatted TOTP secret. It is only present in the
	// response that creates a device_totp method; store it immediately.
	SecretKey string `json:"secret_key,omitempty"`
	// CreatedAt is when this instance was created.
	CreatedAt time.Time `json:"created_at"`
	// UpdatedAt is when this instance was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// GetMethod returns the active 2FA method for the account.
func (s *TwoFactorAuthService) GetMethod(ctx context.Context, opts ...RequestOption) (*TwoFactorMethod, error) {
	out := &TwoFactorMethod{}
	if err := s.client.doJSON(ctx, http.MethodGet, "/api/v2/twofactorauth/method/current/", nil, nil, out, opts); err != nil {
		return nil, err
	}
	return out, nil
}

// TwoFactorMethodChangeParams are the parameters for
// TwoFactorAuthService.ChangeMethod.
type TwoFactorMethodChangeParams struct {
	// Type is the 2FA method type to switch to.
	Type TwoFactorMethodType `json:"type"`
}

// ChangeMethod changes the default 2FA method. The email method activates
// instantly; a device_totp method must be activated with ActivateMethod. The
// response for device_totp contains the one-time SecretKey.
func (s *TwoFactorAuthService) ChangeMethod(ctx context.Context, params TwoFactorMethodChangeParams, opts ...RequestOption) (*TwoFactorMethod, error) {
	out := &TwoFactorMethod{}
	if err := s.client.doJSON(ctx, http.MethodPost, "/api/v2/twofactorauth/method/", nil, params, out, opts); err != nil {
		return nil, err
	}
	return out, nil
}

// TwoFactorMethodActivateParams are the parameters for
// TwoFactorAuthService.ActivateMethod.
type TwoFactorMethodActivateParams struct {
	// Code1 is a code generated by the 2FA device.
	Code1 string `json:"code_1"`
	// Code2 is the next code generated by the 2FA device; it must differ
	// from Code1.
	Code2 string `json:"code_2"`
}

// ActivateMethod activates a device (TOTP) 2FA method with two consecutive
// codes.
func (s *TwoFactorAuthService) ActivateMethod(ctx context.Context, id int, params TwoFactorMethodActivateParams, opts ...RequestOption) (*TwoFactorMethod, error) {
	out := &TwoFactorMethod{}
	path := "/api/v2/twofactorauth/method/" + strconv.Itoa(id) + "/activate/"
	if err := s.client.doJSON(ctx, http.MethodPost, path, nil, params, out, opts); err != nil {
		return nil, err
	}
	return out, nil
}

// TwoFactorCodeParams are the parameters for TwoFactorAuthService.SubmitCode.
type TwoFactorCodeParams struct {
	// Code is the code received via email or generated by the TOTP device.
	Code string `json:"code"`
	// Recaptcha is the recaptcha token.
	Recaptcha string `json:"recaptcha"`
}

// SubmitCode submits the 2FA code after receiving a 403 with code
// "2fa_needed". After authenticating, replay the originally failed request.
func (s *TwoFactorAuthService) SubmitCode(ctx context.Context, params TwoFactorCodeParams, opts ...RequestOption) error {
	return s.client.doJSON(ctx, http.MethodPost, "/api/v2/twofactorauth/codeauth/", nil, params, nil, opts)
}

// TwoFactorEmailResendResult is the response of
// TwoFactorAuthService.ResendEmailCode.
type TwoFactorEmailResendResult struct {
	// EmailSent reports whether the code email was sent.
	EmailSent bool `json:"email_sent"`
}

// ResendEmailCode resends the 2FA code via email. Only available for the
// email 2FA method.
func (s *TwoFactorAuthService) ResendEmailCode(ctx context.Context, opts ...RequestOption) (*TwoFactorEmailResendResult, error) {
	out := &TwoFactorEmailResendResult{}
	if err := s.client.doJSON(ctx, http.MethodPost, "/api/v2/twofactorauth/email/resend/", nil, nil, out, opts); err != nil {
		return nil, err
	}
	return out, nil
}
